# BASIC SETTINGS
title: Still Lab Website
author: <insert>
email: chris.still@oregonstate.edu
description: <insert> 
twitter_username: <insert> 
github_username: <insert>

# BUILD SETTINGS
 markdown: kramdown 
 theme: minima
