# BASIC SETTINGS
title: Still Lab Website
author: Chris Still
email: chris.still@oregonstate.edu
description: 
twitter_username:
github_username: cjstill2017

# BUILD SETTINGS
 markdown: kramdown 
 theme: minima
